### ISSUE TITLE
[Android] Koin + Room Todo List Sample Project

### ISSUE THREAD

**Issue by LeeOhHyung** [YAPP-16th/Team_Android_2_Client#27]
Branch # (featrue/koin-room-todo)

### 요약
DI 라이브러리인 `Koin`과 내부저장소 라이브러리인 `Room`을 사용해서 간단한 TODO List 어플리케이션 제작

### 기능
* [ ] 할일(Todo) Insert
* [ ] 할일(Todo) Delete
* [ ] 할일(Todo) Update

### 요구사항
* [ ] Koin을 통한 `Adapter`, `ViewModel` 혹은 `Presenter`, `RoomDatabase`, `Dao`, `Repository` 주입
* [ ]  Todo List 입력 받는 Layout 자유롭게 구현
